src/main/java/io/confluent/examples/streams/PageViewRegionExample.java
src/main/java/io/confluent/examples/streams/PageViewRegionExampleDriver.java
src/main/java/io/confluent/examples/streams/PageViewRegionLambdaExample.java
src/main/resources/avro/io/confluent/examples/streams/pageviewregion.avsc

- Comment to create the unneccessary 'PageViewsByUser' removed.
- Used try..resources to close the producer and consumer.
(cherry picked from commit a13f98c)

Typo error corrected in the pageviewregion.avsc

---

Dockerfile
Jenkinsfile
pom.xml
requirements.txt
setup.py
test/fixtures/standalone-config.yml
test/fixtures/standalone-network.yml
test/test_kafka_streams_examples.py
tox.ini

These are the old tests from cp-docker-images, updated to run without docker-machine.

add docker image tests + run them in CI

---

src/main/java/io/confluent/examples/streams/WordCountLambdaExample.java

Here for the reference https://github.com/confluentinc/docs/blob/3.3.x/streams/quickstart.rst

3.3.x: Modify topic names to be aligned with docs

---

src/main/java/io/confluent/examples/streams/microservices/OrderDetailsService.java

typo - incorrect method call in main()

boolean running is never set to true

---

src/test/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExampleTest.java

This test failed with
```
java.lang.AssertionError: 
Expected: <1>
but: was <0>
at io.confluent.examples.streams.interactivequeries.WordCountInteractiveQueriesExampleTest.shouldDemonstrateInteractiveQueries(WordCountInteractiveQueriesExampleTest.java:220)
```
We need to wait until all data is processed before we can start querying the stores.

Fix flaky test WordCountInteractiveQueriesExample

---

src/test/java/io/confluent/examples/streams/GlobalKTablesExampleTest.java
src/test/java/io/confluent/examples/streams/microservices/EmailServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/EndToEndTest.java
src/test/java/io/confluent/examples/streams/microservices/FraudServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/util/MicroserviceTestUtils.java

- increase RS timeout (for two tests)
- some code cleanup

KAFKA-1166: fix flaky EndToEnd integration test

---

src/main/java/io/confluent/examples/streams/microservices/EmailService.java
src/main/java/io/confluent/examples/streams/microservices/FraudService.java
src/main/java/io/confluent/examples/streams/microservices/InventoryService.java
src/main/java/io/confluent/examples/streams/microservices/OrderDetailsService.java
src/main/java/io/confluent/examples/streams/microservices/OrdersService.java
src/main/java/io/confluent/examples/streams/microservices/ValidationsAggregatorService.java
src/test/java/io/confluent/examples/streams/microservices/EndToEndTest.java
src/test/java/io/confluent/examples/streams/microservices/OrderDetailsServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/ValidationsAggregatorServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/util/MicroserviceTestUtils.java

Also:
- Fixed up microservices code to use the new version of the API.
- Changed the ValidationsAggregatorService to use session windows (hopping windows fail consistently on this version).

Merge 3.0 branch --> 4.0 branch

---

src/test/java/io/confluent/examples/streams/WikipediaFeedAvroLambdaExampleTest.java

Test failed with
```
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
```
This PR aims to make it more stable.

MINOR: increase ZK timeout for WikipediaFeedAvroLambdaExampleTest

---

src/main/java/io/confluent/examples/streams/MapFunctionLambdaExample.java
src/test/java/io/confluent/examples/streams/FanoutLambdaIntegrationTest.java
src/test/java/io/confluent/examples/streams/MapFunctionLambdaIntegrationTest.java
src/test/java/io/confluent/examples/streams/MixAndMatchLambdaIntegrationTest.java

Sync with Ismael, and we decided that a lambda is better than the cast.

MINOR: follow up for KIP-149

---

src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java

Added configs for Schema Registry in an effort to see if this helps with examples tests flakiness since most of the failure involve Schema Registry
- Increased store init timeout to 90 seconds
- Increased store operation timeout from 500ms to 10s
- Set debug flag to true

MINOR: adding schema registry configs

---

src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java

MINOR: reverting back to constructor taking props

---

src/test/scala/io/confluent/examples/streams/algebird/CMSStoreTest.scala

Unfortunately we cannot use the newly added MockProcessorContext still in this test, and eventually we need https://issues.apache.org/jira/browse/KAFKA-6460 to completely get rid of the o.a.k.test classes here.

Rename MockProcessorContext to InternalMockProcessorContext

---

pom.xml
src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java

MINOR: fix pom for Eclipse

---

src/main/java/io/confluent/examples/streams/AnomalyDetectionLambdaExample.java
src/main/java/io/confluent/examples/streams/ApplicationResetExample.java
src/main/java/io/confluent/examples/streams/MapFunctionLambdaExample.java
src/main/java/io/confluent/examples/streams/PageViewRegionExample.java
src/main/java/io/confluent/examples/streams/PageViewRegionLambdaExample.java
src/main/java/io/confluent/examples/streams/SecureKafkaStreamsExample.java
src/main/java/io/confluent/examples/streams/SumLambdaExample.java
src/main/java/io/confluent/examples/streams/UserRegionLambdaExample.java
src/main/java/io/confluent/examples/streams/WordCountLambdaExample.java
src/main/scala/io/confluent/examples/streams/MapFunctionScalaExample.scala
src/main/scala/io/confluent/examples/streams/WordCountScalaExample.scala

Remove refs to `--new-consumer` otherwise users get an error of `new-consumer is not a recognized option`.

KSTREAMS-1609: Remove refs to --new-consumer

---

pom.xml

Already set at https://github.com/confluentinc/common/blob/4.1.x/pom.xml#L93
Testing: `mvn package -Pdocker` works as expected / same as other repos

Remove docker properties so we use the ones from common

---

docker-compose.yml

Need to update refs to `kafka-streams-examples` in `docker-compose.yml` to `5.0.0`

MINOR: Update refs of kafka-streams-examples-4.1.0 to 5.0.0

---

src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExample.java
src/test/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExampleTest.java

Fix race condition by waiting for expected output in stores

KSTREAM-1647: Fix KafkaMusicExampleTest

---

docs/index.rst
pom.xml
src/main/java/io/confluent/examples/streams/WikipediaFeedAvroExample.java
src/main/java/io/confluent/examples/streams/utils/MonitoringInterceptorUtils.java

Example for making implementing `MonitoringInterceptors` easier when working with CE and C3

KSTREAMS-1621: Initial integration of monitoring interceptors

---

src/main/java/io/confluent/examples/streams/microservices/EmailService.java
src/main/java/io/confluent/examples/streams/microservices/ValidationsAggregatorService.java

DEVX-244: fix serdes in ValidationsAggregatorService

---

src/main/java/io/confluent/examples/streams/microservices/ValidationsAggregatorService.java

Another case of running `pint merge` and non-final variables

MINOR: Set variables to final

---

src/main/java/io/confluent/examples/streams/microservices/AddInventory.java
src/main/java/io/confluent/examples/streams/microservices/PostOrdersAndPayments.java
src/main/java/io/confluent/examples/streams/microservices/util/ConsumeCustomers.java
src/main/java/io/confluent/examples/streams/microservices/util/ConsumeOrders.java
src/main/java/io/confluent/examples/streams/microservices/util/ConsumePayments.java
src/main/java/io/confluent/examples/streams/microservices/util/ProduceCustomers.java
src/main/java/io/confluent/examples/streams/microservices/util/ProduceOrders.java
src/main/java/io/confluent/examples/streams/microservices/util/ProducePayments.java

Hey @ybyzek ,
I just loaded up the PR in IDEA and did the following:
* reformat to match code style
* remove unused imports
* fix broken package name on the "utils" classes
* resolve compiler warnings (particularly about the infinite loops)
* remove unused variables
* remove unused `throws` declarations
* replace deprecated `poll` method

#165 code review

---

.gitignore
Jenkinsfile
test/test_kafka_streams_examples.py

Depends on https://github.com/confluentinc/jenkins-common/pull/75

 Remove use of deprecated docker_oraclejdk8 and use correct default tag

---

src/main/java/io/confluent/examples/streams/ApplicationResetExample.java
src/test/java/io/confluent/examples/streams/ApplicationResetIntegrationTest.java

See https://github.com/confluentinc/kafka-streams-examples/issues/175

ApplicationResetExample: bugfix for the --reset flag

---

README.md

Improve README file with IntelliJ/Eclipse instructions

---

README.md
src/main/java/io/confluent/examples/streams/microservices/EmailService.java
src/main/java/io/confluent/examples/streams/microservices/README.md
src/main/java/io/confluent/examples/streams/microservices/domain/Schemas.java
src/main/java/io/confluent/examples/streams/microservices/util/ProduceCustomers.java
src/main/resources/avro/io/confluent/examples/streams/microservices/customer.avsc
src/main/resources/avro/io/confluent/examples/streams/microservices/orderenriched.avsc
src/test/java/io/confluent/examples/streams/microservices/EmailServiceTest.java

The goal of this PR is to show dynamic routing using TopicNameExtractor
This PR also fixes https://github.com/confluentinc/kafka-streams-examples/issues/189

DEVX-544: dynamic routing example

---

src/main/java/io/confluent/examples/streams/JsonToAvroExample.java
src/main/java/io/confluent/examples/streams/JsonToAvroExampleDriver.java

This PR is a simple example of converting records stored in JSON format to Avro

MINOR: Example for simple stream app to convert JSON to Avro

---

src/test/java/io/confluent/examples/streams/microservices/util/MicroserviceTestUtils.java

This PR increases the timeout for reading records in `MicroserviceTestUtils` and some minor cleanup that I figured I take care of at the same time.

MINOR: Increase timeout, minor cleanup as well

---

src/test/java/io/confluent/examples/streams/microservices/EndToEndTest.java
src/test/java/io/confluent/examples/streams/microservices/OrdersServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/util/MicroserviceTestUtils.java

Follow up to #212 -- adding retires to POST, too.

Add retries to REST POST calls

---

README.md

This is a series of fixes on readme from 5.0.0-post till master.

KSTREAMS-2772: 5.0.0-post readme

---

README.md
docker-compose.yml
pom.xml
src/main/java/io/confluent/examples/streams/microservices/README.md
src/test/java/io/confluent/examples/streams/CustomStreamTableJoinIntegrationTest.java
src/test/java/io/confluent/examples/streams/IntegrationTestUtils.java
src/test/java/io/confluent/examples/streams/utils/InstantDeserializer.java
src/test/java/io/confluent/examples/streams/utils/InstantSerde.java
src/test/java/io/confluent/examples/streams/utils/InstantSerdeTest.java
src/test/java/io/confluent/examples/streams/utils/InstantSerializer.java
src/test/java/io/confluent/examples/streams/utils/KeyValueWithTimestamp.java
src/test/java/io/confluent/examples/streams/utils/Pair.java
src/test/java/io/confluent/examples/streams/utils/PairDeserializer.java
src/test/java/io/confluent/examples/streams/utils/PairOfDoubleAndLongDeserializer.java
src/test/java/io/confluent/examples/streams/utils/PairSerde.java
src/test/java/io/confluent/examples/streams/utils/PairSerdeTest.java
src/test/java/io/confluent/examples/streams/utils/PairSerializer.java
src/test/java/io/confluent/examples/streams/utils/PairTest.java
src/test/java/io/confluent/examples/streams/utils/PriorityQueueSerdeTest.java

New PR for `5.2.1-post`, based on https://github.com/confluentinc/kafka-streams-examples/pull/197.

Add custom stream-table join example where the table triggers updates, too

---

src/main/java/io/confluent/examples/streams/SumLambdaExample.java
src/test/java/io/confluent/examples/streams/IntegrationTestUtils.java
src/test/java/io/confluent/examples/streams/SumLambdaIntegrationTest.java
src/test/java/io/confluent/examples/streams/TableToTableJoinIntegrationTest.java

A continuation of #242 . Porting integration tests to TopologyTestDriver, where applicable.

Minor improve test stability 2

---

src/test/java/io/confluent/examples/streams/PassThroughIntegrationTest.java
src/test/java/io/confluent/examples/streams/StateStoresInTheDSLIntegrationTest.java
src/test/java/io/confluent/examples/streams/StreamToStreamJoinIntegrationTest.java
src/test/java/io/confluent/examples/streams/StreamToTableJoinIntegrationTest.java

Continuing on the work of #242 and #245 , port four more tests.

MINOR: port more tests to TopologyTestDriver

---

src/test/java/io/confluent/examples/streams/window/CustomWindowTest.java
src/test/java/io/confluent/examples/streams/window/DailyTimeWindows.java

Here is a basic example of a custom daily window starting every day at 6pm.
It also shows a potential problem with timezone having daylight saving time (https://en.wikipedia.org/wiki/Daylight_saving_time).

Add a sample of custom window

---

README.md

* Updated Version Compatibility Matrix
* Updated version references under "Packaging and Running the Application Examples"

Updated versions in README for 5.3

---

docker-compose.yml
docs/index.rst
src/main/java/io/confluent/examples/streams/AnomalyDetectionLambdaExample.java
src/main/java/io/confluent/examples/streams/ApplicationResetExample.java
src/main/java/io/confluent/examples/streams/GlobalKTablesExample.java
src/main/java/io/confluent/examples/streams/GlobalKTablesExampleDriver.java
src/main/java/io/confluent/examples/streams/JsonToAvroExample.java
src/main/java/io/confluent/examples/streams/JsonToAvroExampleDriver.java
src/main/java/io/confluent/examples/streams/MapFunctionLambdaExample.java
src/main/java/io/confluent/examples/streams/PageViewRegionExample.java
src/main/java/io/confluent/examples/streams/PageViewRegionExampleDriver.java
src/main/java/io/confluent/examples/streams/PageViewRegionLambdaExample.java
src/main/java/io/confluent/examples/streams/SecureKafkaStreamsExample.java
src/main/java/io/confluent/examples/streams/SessionWindowsExample.java
src/main/java/io/confluent/examples/streams/SessionWindowsExampleDriver.java
src/main/java/io/confluent/examples/streams/SumLambdaExample.java
src/main/java/io/confluent/examples/streams/SumLambdaExampleDriver.java
src/main/java/io/confluent/examples/streams/TopArticlesExampleDriver.java
src/main/java/io/confluent/examples/streams/TopArticlesLambdaExample.java
src/main/java/io/confluent/examples/streams/UserRegionLambdaExample.java
src/main/java/io/confluent/examples/streams/WikipediaFeedAvroExample.java
src/main/java/io/confluent/examples/streams/WikipediaFeedAvroExampleDriver.java
src/main/java/io/confluent/examples/streams/WikipediaFeedAvroLambdaExample.java
src/main/java/io/confluent/examples/streams/WordCountLambdaExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesDriver.java
src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExampleDriver.java
src/main/scala/io/confluent/examples/streams/MapFunctionScalaExample.scala
src/main/scala/io/confluent/examples/streams/WordCountScalaExample.scala

Also fix 5.2.1-standalone.jar references in the javadocs to 5.3.0
+ add "-SNAPSHOT" to docker-compose

Use 5.3.0-post branch instead of master

---

docker-compose.yml

@ableegoldman I created a different PR retargeting against 5.1.3-post. Same with #279 with a different base branch.

Fix empty response from server when running curl on music demo app

---

README.md
docker-compose.yml
src/main/java/io/confluent/examples/streams/AnomalyDetectionLambdaExample.java
src/main/java/io/confluent/examples/streams/ApplicationResetExample.java
src/main/java/io/confluent/examples/streams/GlobalKTablesExample.java
src/main/java/io/confluent/examples/streams/GlobalKTablesExampleDriver.java
src/main/java/io/confluent/examples/streams/JsonToAvroExample.java
src/main/java/io/confluent/examples/streams/JsonToAvroExampleDriver.java
src/main/java/io/confluent/examples/streams/MapFunctionLambdaExample.java
src/main/java/io/confluent/examples/streams/PageViewRegionExample.java
src/main/java/io/confluent/examples/streams/PageViewRegionExampleDriver.java
src/main/java/io/confluent/examples/streams/PageViewRegionLambdaExample.java
src/main/java/io/confluent/examples/streams/SecureKafkaStreamsExample.java
src/main/java/io/confluent/examples/streams/SessionWindowsExample.java
src/main/java/io/confluent/examples/streams/SessionWindowsExampleDriver.java
src/main/java/io/confluent/examples/streams/SumLambdaExample.java
src/main/java/io/confluent/examples/streams/SumLambdaExampleDriver.java
src/main/java/io/confluent/examples/streams/TopArticlesExampleDriver.java
src/main/java/io/confluent/examples/streams/TopArticlesLambdaExample.java
src/main/java/io/confluent/examples/streams/UserRegionLambdaExample.java
src/main/java/io/confluent/examples/streams/WikipediaFeedAvroExample.java
src/main/java/io/confluent/examples/streams/WikipediaFeedAvroExampleDriver.java
src/main/java/io/confluent/examples/streams/WikipediaFeedAvroLambdaExample.java
src/main/java/io/confluent/examples/streams/WordCountLambdaExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesDriver.java
src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExampleDriver.java
src/main/scala/io/confluent/examples/streams/MapFunctionScalaExample.scala
src/main/scala/io/confluent/examples/streams/WordCountScalaExample.scala

Tools is adding a regex to catch these so they won't slip going forward

Bump jar versions

---

checkstyle/suppressions.xml
src/test/java/io/confluent/examples/streams/microservices/util/MicroserviceTestUtils.java

Not sure why this is suddenly necessary.

MINOR: fix broken build due to missing suppressions file

---

Jenkinsfile

Stop notifying in Slack, so we can get tickets instead.

Remove slackChannel from Jenkinsfile

---

Jenkinsfile

I am disabling the cron schedule because it will always fail because these builds require parameters to be passed in.

Disable cron schedule

---

README.md

See https://github.com/apache/kafka/pull/7677 for more details with regards to
the former and https://github.com/apache/kafka/pull/6031 with regards to the latter.

Replace `./gradlew installAll` with `./gradlewAll install and remove invocation of `gradle`

---

README.md

Remove SNAPSHOT and update version number in README

---

pom.xml
src/test/scala/io/confluent/examples/streams/AggregateScalaTest.scala
src/test/scala/io/confluent/examples/streams/GenericAvroScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/IntegrationTestScalaUtils.scala
src/test/scala/io/confluent/examples/streams/ProbabilisticCountingScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/ReduceScalaTest.scala
src/test/scala/io/confluent/examples/streams/SpecificAvroScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/StreamToTableJoinScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/WordCountScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/algebird/CMSStoreTest.scala
src/test/scala/io/confluent/examples/streams/algebird/TopCMSSerdeTest.scala

Thanks to our dear scalatest there's a bunch of breaking changes that need to be fixed.

Move to scala 2.13

---

src/main/java/io/confluent/examples/streams/microservices/PostOrdersAndPayments.java

This allows the service to continue to try and post orders while the OrdersService is unavailable
or not yet ready.

DEVX-1867: microservices: added exception hdlr for PostOrdersAndPayments

---

docs/index.rst

Fixes https://confluentinc.atlassian.net/browse/DEVX-2307
Validated with local docs build

DEVX-2307: An empty code samples in music demo

---

Jenkinsfile

Not sure if this is the right channel... Let me know if it should do somewhere else.
We want to eventually archive `#streams-alerts` channel.

Update alert Slack channel

---

src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExample.java

See discussion on https://issues.apache.org/jira/browse/KAFKA-12446
and https://github.com/confluentinc/kafka-streams-examples/issues/380

Add warning re TopFiveSongs aggregator

---

src/main/java/io/confluent/examples/streams/GlobalStoresExample.java
src/main/java/io/confluent/examples/streams/TopArticlesExampleDriver.java
src/main/java/io/confluent/examples/streams/TopArticlesLambdaExample.java
src/main/java/io/confluent/examples/streams/WikipediaFeedAvroExample.java
src/main/java/io/confluent/examples/streams/microservices/FraudService.java
src/main/java/io/confluent/examples/streams/microservices/InventoryService.java
src/main/java/io/confluent/examples/streams/microservices/PostOrdersAndPayments.java
src/main/java/io/confluent/examples/streams/microservices/domain/Schemas.java
src/main/scala/io/confluent/examples/streams/MapFunctionScalaExample.scala
src/main/scala/io/confluent/examples/streams/WordCountScalaExample.scala
src/main/scala/io/confluent/examples/streams/algebird/CMSStore.scala
src/main/scala/io/confluent/examples/streams/algebird/CMSStoreChangeLogger.scala
src/main/scala/io/confluent/examples/streams/algebird/ProbabilisticCounter.scala
src/test/java/io/confluent/examples/streams/GenericAvroIntegrationTest.java
src/test/java/io/confluent/examples/streams/TopArticlesLambdaExampleTest.java
src/test/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExampleTest.java
src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java
src/test/java/io/confluent/examples/streams/window/CustomWindowTest.java
src/test/scala/io/confluent/examples/streams/AggregateScalaTest.scala
src/test/scala/io/confluent/examples/streams/GenericAvroScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/IntegrationTestScalaUtils.scala
src/test/scala/io/confluent/examples/streams/ProbabilisticCountingScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/ReduceScalaTest.scala
src/test/scala/io/confluent/examples/streams/SpecificAvroScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/StreamToTableJoinScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/WordCountScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/algebird/CMSStoreTest.scala
src/test/scala/io/confluent/examples/streams/algebird/TopCMSSerdeTest.scala

Added compiler warnings about deprecated API usage. Plus a few minor cleanups.

MINOR: fix compiler warnings

---

src/main/java/io/confluent/examples/streams/GlobalStoresExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/MetadataService.java
src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesRestService.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/MusicPlaysRestService.java
src/main/java/io/confluent/examples/streams/microservices/domain/Schemas.java

1. Remove deprecated usage of "schema.registry.basic.auth.user.info"
2. Replace deprecated state store usage.
Local tested with mvn clean compile test 
#336

Bug-fix 336

---

src/main/java/io/confluent/examples/streams/microservices/OrderDetailsService.java
src/main/scala/io/confluent/examples/streams/algebird/CMSStoreChangeLogger.scala
src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java
src/test/java/io/confluent/examples/streams/kafka/KafkaEmbedded.java
src/test/java/io/confluent/examples/streams/microservices/util/MicroserviceTestUtils.java

Some internal APIs got removed via
https://github.com/apache/kafka/pull/10872

HOTFIX: fix compile errors

---

src/main/scala/io/confluent/examples/streams/algebird/CMSStoreChangeLogger.scala

Uses an internal API...which was modified...and here we are 🙃

Fix build due to internal API usage

---

src/main/java/io/confluent/examples/streams/SumLambdaExampleDriver.java

MINOR: Fix sum-lambda example

---

.github/CODEOWNERS

https://confluentinc.atlassian.net/browse/KSE-750

chore: add CODEOWNERS file (MINOR)

---

pom.xml

[KCI-1900](https://confluentinc.atlassian.net/browse/KCI-1900): Migrate from log4j to reload4j to fix CVEs

security fix: Migrate from log4j to reload4j

---

pom.xml
src/test/java/io/confluent/examples/streams/ApplicationResetIntegrationTest.java

Build failure because of https://github.com/apache/kafka/pull/13127/files#diff-91ad95abb091fce561c67463a30139bc2404e29fcdf67e80d91ed45a09bfcbc7

[KSQL-10378] Fix package

---

src/main/java/io/confluent/examples/streams/WordCountLambdaExample.java

Just corrected a typo in one of the comments.
As a first time contributor, I'm taking a guess at who to tag for review. I looked (admittedly briefly) for a first-time contributor guide and didn't see one for this repo.
Reviewer - @mjsax

Corrected small spelling error

---

pom.xml

Upstream ZK version bump, requires to add new dependency.

MINOR: fix broken build

---

pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 6.1.x to 6.2.x)

---

Jenkinsfile
pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 5.1.x to 5.2.x)

---

Jenkinsfile

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 5.3.x to 5.4.x)

---

service.yml

Creeating service.yml following the migration guide:
https://confluentinc.atlassian.net/wiki/x/E4xuvw

KSTREAMS-5725: First attempt at semaphore configuration

---

Jenkinsfile

MINOR: update slack alert channel

---

.github/CODEOWNERS

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 7.1.x to 7.2.x)

---

src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java

This reverts commit 909f9d6ca6d0d9a9cf7e98b85cda889e29932b1c.

Revert "MINOR: fix compilation error (#476)"

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml

This is a routine update from cc-service-bot based on the service.yml in your repo. This PR
should be approved and merged as soon as CI passes.

chore: update repo by service bot

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/project.yml
.semaphore/semaphore.yml
service.yml
sonar-project.properties

See comments in KSTREAMS-5737 -- apprently we need to do this

KSTREAMS-5737: Backport semaphore configuration to oldest supported CP branch

---

.semaphore/project.yml
.semaphore/semaphore.yml
service.yml

Oldest active CP branch apparently needs those changes as well.

KSTREAMS-5737: Backport semaphore changes to 6.2.x

---

service.yml

We were asked to add those tasks to semaphore (see ticket).

KSTREAMS-5737: Add tasks

---

service.yml

See https://confluent.slack.com/archives/C06N5PM0W0G/p1716356782234999

KSTREAMS-5737: Enable push_latest parameter

---

service.yml

The reserved repos are removed.

Update service.yml: remove artifact path
