confluentinc/kafka-streams-examples

src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExample.java

This PR fixes the following issue: the starting application command within the documentation of the WordCountInteractive queries example was not pointing to the proper main class.
A previous PR was created in the [confluentinc-examples](https://github.com/confluentinc/examples/pull/149) repo and as per @mjsax comment I created this one as well.

Fix doc: proper main class in the start instance command

---

pom.xml
src/main/java/io/confluent/examples/streams/microservices/OrderDetailsService.java

The current version of OrderService blows on POST request with 
javax.servlet.ServletException: java.lang.UnsupportedOperationException: Asynchronous processing not supported on Servlet 2.x container.
jersey-container-servlet needs to be a dependency since it is servlet 3.x implementation, not jersey-container-servlet-core which is servlet 2.x implementation. See https://mvnrepository.com/artifact/org.glassfish.jersey.containers/jersey-container-servlet-core and https://mvnrepository.com/artifact/org.glassfish.jersey.containers/jersey-container-servlet

The incorrect jersey-container-servlet-core dependency forces servlet 2.x implementation that makes async request fail. 

---

src/main/scala/io/confluent/examples/streams/MapFunctionScalaExample.scala

Needed to add `--property print.key=true` for example

add print.key property for example

---

src/main/java/io/confluent/examples/streams/microservices/OrdersService.java
src/test/java/io/confluent/examples/streams/ValidateStateWithInteractiveQueriesLambdaIntegrationTest.java
src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java
src/test/java/io/confluent/examples/streams/kafka/KafkaEmbedded.java
src/test/java/io/confluent/examples/streams/microservices/EmailServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/OrdersServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/util/MicroserviceTestUtils.java

OrderServiceTest need to cleanup the used order-topic between tests. Otherwise, the test does not start with a clean test environment.
The test sometimes fails with
```
org.junit.ComparisonFailure: expected:<...customerId=2, state=[CRE]ATED, product=JUMPER...> but was:<...customerId=2, state=[VALID]ATED, product=JUMPER...>
at io.confluent.examples.streams.microservices.OrdersServiceTest.shouldPostOrderAndGetItBack(OrdersServiceTest.java:79)
```
Updating the customer-id in each test case shows, that data from another test run is consumed:
```
org.junit.ComparisonFailure: expected:<...{id='1', customerId=[4], state=VALIDATED, p...> but was:<...{id='1', customerId=[3], state=VALIDATED, p...>
at io.confluent.examples.streams.microservices.OrdersServiceTest.shouldGetOrderByIdWhenOnDifferentHost …
```

MINOR: Fix incorrect OrderServiceTest

---

src/main/java/io/confluent/examples/streams/WordCountLambdaExample.java

Minor inconsistency which confused me for a moment, as I initially created the topics and started the producer/consumer as described in the comments, which does not work.
s/WordsWithCountsTopic/streams-wordcount-output/g
s/TextLinesTopic/streams-plaintext-input/g

MINOR: fix inconsistency between comments and code in WordCountLambdaExample

---

src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java

Taking out changes for setting `RestApp` properties until 3.3.2 is released.

MINOR: take out fix until 3.3.2 is released

---

src/main/java/io/confluent/examples/streams/microservices/EmailService.java
src/main/java/io/confluent/examples/streams/microservices/FraudService.java
src/main/java/io/confluent/examples/streams/microservices/InventoryService.java
src/main/java/io/confluent/examples/streams/microservices/OrderDetailsService.java
src/main/java/io/confluent/examples/streams/microservices/OrdersService.java
src/main/java/io/confluent/examples/streams/microservices/Service.java
src/main/java/io/confluent/examples/streams/microservices/ValidationsAggregatorService.java
src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java
src/test/java/io/confluent/examples/streams/microservices/EmailServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/EndToEndTest.java
src/test/java/io/confluent/examples/streams/microservices/FraudServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/InventoryServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/OrderDetailsServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/OrdersServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/ValidationsAggregatorServiceTest.java

Change the microservices tests etc to not use /tmp/kafka-streams.
Increased timeout in `EmailServiceTest` to 30 seconds
Reduce number of consumer-offset partitions in `EmbeddedKafka` as 50 is overkill for tests.

don't use /tmp/kafka-streams as state.dir in microservices tests

---

docker-compose.yml

**Important:** This PR must only be merged once we published a 4.1.0 tagged image for https://hub.docker.com/r/confluentinc/kafka-streams-examples/.

Use CP 4.1.0 docker images for 4.1 branches

---

pom.xml

rest-utils upgraded to latest versions of jetty and jersey, needed to update version of javax.ws.rs-api

MINOR: Bump version javax.ws.rs

---

src/main/java/io/confluent/examples/streams/microservices/EmailService.java

Serdes must be initialised with the schema registry but are being cached in a static Joined variable before the schema registry is configured.

Serdes cached in static variable

---

src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesRestService.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/MusicPlaysRestService.java
src/test/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExampleTest.java
src/test/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExampleTest.java
src/test/resources/song_source.csv

Currently, any string provided as the APPLICATION_HOST will start the REST Service on localhost (0.0.0.0).
This fix will enhance the functionality by- 
- Validating the HOST and raising the exception for any invalid/ unreachable/ unavailable host.
- Starts the REST service on the provided host and port (If valid). 
Issue link: https://github.com/confluentinc/kafka-streams-examples/issues/127

Fixed host issue for kafka-interactive-queries

---

src/main/scala/io/confluent/examples/streams/algebird/CMSStoreBuilder.scala

We updated this interface in:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-356%3A+Add+withCachingDisabled%28%29+to+StoreBuilder?src=jira
https://issues.apache.org/jira/browse/KAFKA-6998
https://github.com/apache/kafka/commit/0d778987ee3b920b5c876696385c0792671adef8
It was a breaking API change.

KSTREAMS-1687: CMSStoreBuilder implement new iface

---

src/test/java/io/confluent/examples/streams/ExampleTestUtils.java
src/test/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExampleTest.java
src/test/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExampleTest.java
src/test/resources/log4j.properties

1. The actual fix of the flakiness: we need to include the comparison of the expected result with the actual result into the `waitForCondition` as well to allow retries. Before that we only wait for the query to return the expected number of entries, but not all entries have been updated to date.
2. Cleanup: on the two interactivequeries tests, we have duplicated tests one for `host = localhost` and one for `host = 127.10.10.10` just to test that any valid host should work. I've consolidated them to generate a random valid host each time.

Fix flaky interactive query tests

---

src/main/java/io/confluent/examples/streams/microservices/EmailService.java

Missed this during review, `serdes` variable should be `final`.

MINOR: Make serdes final

---

src/main/java/io/confluent/examples/streams/WikipediaFeedAvroExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesDriver.java
src/main/java/io/confluent/examples/streams/utils/MonitoringInterceptorUtils.java
src/test/java/io/confluent/examples/streams/GlobalKTablesExampleTest.java
src/test/java/io/confluent/examples/streams/TopArticlesLambdaExampleTest.java

Refactored `MonitoringInterceptorUtils` to be able to configure individual producers and consumers in addition to configuring a streams application with Confluent Monitoring interceptors.
For testing, I picked two tests and added configuration for monitoring interceptors and confirmed configuration and usage via logs.

KSTREAMS-1712: Add option for configuring Producers, Consumers with interceptors

---

README.md

As per https://github.com/confluentinc/kafka-streams-examples/issues/160#issuecomment-419818275

Document scala java compatibility

---

pom.xml
src/test/scala/io/confluent/examples/streams/GenericAvroScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/ProbabilisticCountingScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/SpecificAvroScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/StreamToTableJoinScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/WordCountScalaIntegrationTest.scala

We upgraded to Scala 2.12 in the common pom and we had to upgrade the
scalatest dependency to get a build for that Scala version.
The assert4J change is due to an overload ambiguity when using Scala 2.12.

Use scala-library 2.12.7 and replace assert4J with scalatest assert

---

src/test/java/io/confluent/examples/streams/GlobalKTablesExampleTest.java
src/test/java/io/confluent/examples/streams/microservices/util/MicroserviceTestUtils.java

`EndToEndTest.shouldProcessManyInvalidOrdersEndToEnd` failed in https://jenkins.confluent.io/job/confluentinc/job/kafka-streams-examples/job/3.3.x/727 with
```
javax.ws.rs.ServerErrorException: HTTP 504 Gateway Timeout
at io.confluent.examples.streams.microservices.EndToEndTest.shouldProcessManyInvalidOrdersEndToEnd(EndToEndTest.java:121)
```
This is a known issue and was fixed with https://github.com/confluentinc/kafka-streams-examples/pull/41 in `4.0` already -- not sure why we did not do the fix in `3.3` to begin with.
This PR back ports the fix (ie, increase SR timeout) only (not the applied code cleanup).
When merging, this should not to into 4.0 and later branches.

Increase SR timeout; backport of PR #41

---

pom.xml
src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesRestService.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExample.java
src/main/java/io/confluent/examples/streams/microservices/domain/Schemas.java
src/main/scala/io/confluent/examples/streams/MapFunctionScalaExample.scala
src/main/scala/io/confluent/examples/streams/WordCountScalaExample.scala
src/test/java/io/confluent/examples/streams/ApplicationResetIntegrationTest.java
src/test/java/io/confluent/examples/streams/GlobalKTablesExampleTest.java
src/test/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExampleTest.java
src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java
src/test/java/io/confluent/examples/streams/kafka/KafkaEmbedded.java

Setting fail-on-warn and resolving all warnings in one PR turned out to be too large a change, and also hard to debug (see https://github.com/confluentinc/kafka-streams-examples/pull/201).
Instead, this change just enables the warnings, and then resolves some of the warnings.
We can follow up by tackling more warnings in another PR.

MINOR: Fix some compiler warnings

---

src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java
src/test/java/io/confluent/examples/streams/kafka/KafkaEmbedded.java

We've recently started seeing errors in the examples test due to race condition when using the `AdminClient` to confirm if a topic has been deleted.
The failure shows up in the logs with the failure to create the topic as it still exists as the test condition returned `true`
```
[2019-03-06 01:55:15,914] INFO [data-plane-kafka-request-handler-0] [Admin Manager on Broker 0]: Error processing create topic request for topic orders with arguments (numPartitions=1, replicationFactor=1, replicasAssignments={}, configs={}) (kafka.server.AdminManager)
org.apache.kafka.common.errors.TopicExistsException: Topic 'orders' already exists.
```
And a little later in the log we see the actual deletion taking place
```
[2019-03-06 01:55:15,941] INFO [controller-event-thread] [Topic Deletion Manager 0], …
```

MINOR: Need to use ZK client on broker to confirm topics deleted

---

pom.xml
src/test/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExampleTest.java
src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java

3.3.2 was release a while ago. This PR applies a fix as described in the comment.
This PR is for 3.3.0 and 3.3.1 -- in 3.3.2 and newer we can change the `pom.xml` dependency back to `${confluent.version}`.
This fix does not go into 4.x or newer branches as describe in the comment.

Enable SR fix for 3.3.x branches (do not merged to 4.x or newer)

---

pom.xml

Follow up to #213: set SR version to current version
The fix from #213 was only required for 3.3.0 and 3.3.1 to get newer SR version 3.3.2 that contains a fix we depend on.

Fix SR version

---

pom.xml

`groupId` is inherited from parent pom

Remove redundant groupId

---

pom.xml

This is easier to manage centrally to make sure updates are applied everywhere and checkstyle in particular doesn't tend to cause many problems when updated centrally.

MINOR: Use checkstyle version from common pom which is newer and makes keeping this repo up to date easier

---

pom.xml
src/test/java/io/confluent/examples/streams/IntegrationTestUtils.java
src/test/java/io/confluent/examples/streams/UserCountsPerRegionLambdaIntegrationTest.java

Migrate `UserCountsPerRegionLambdaIntegrationTest` to TopologyTestDriver. The first of many, others will follow.

MINOR: Use TopologyTestDriver for UserCountsPerRegionLambdaIntegrationTest

---

src/main/scala/io/confluent/examples/streams/algebird/ProbabilisticCounter.scala
src/test/java/io/confluent/examples/streams/EventDeduplicationLambdaIntegrationTest.java
src/test/java/io/confluent/examples/streams/FanoutLambdaIntegrationTest.java
src/test/java/io/confluent/examples/streams/HandlingCorruptedInputRecordsIntegrationTest.java
src/test/java/io/confluent/examples/streams/MapFunctionLambdaIntegrationTest.java
src/test/java/io/confluent/examples/streams/MixAndMatchLambdaIntegrationTest.java
src/test/java/io/confluent/examples/streams/PassThroughIntegrationTest.java
src/test/java/io/confluent/examples/streams/StateStoresInTheDSLIntegrationTest.java
src/test/java/io/confluent/examples/streams/StreamToStreamJoinIntegrationTest.java
src/test/java/io/confluent/examples/streams/StreamToTableJoinIntegrationTest.java
src/test/java/io/confluent/examples/streams/SumLambdaIntegrationTest.java
src/test/java/io/confluent/examples/streams/TableToTableJoinIntegrationTest.java
src/test/java/io/confluent/examples/streams/UserCountsPerRegionLambdaIntegrationTest.java
src/test/java/io/confluent/examples/streams/ValidateStateWithInteractiveQueriesLambdaIntegrationTest.java
src/test/java/io/confluent/examples/streams/WordCountLambdaIntegrationTest.java
src/test/scala/io/confluent/examples/streams/ProbabilisticCountingScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/StreamToTableJoinScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/WordCountScalaIntegrationTest.scala

Continue the work of #242 , #245 , and #246 by porting the rest of the integration tests that don't use Schema Registry.
The Schema Registry tests will get ported in a later PR.

MINOR: port more tests to TopologyTestDriver

---

src/test/java/io/confluent/examples/streams/GenericAvroIntegrationTest.java
src/test/java/io/confluent/examples/streams/utils/MockGenericAvroDeserializer.java
src/test/java/io/confluent/examples/streams/utils/MockGenericAvroSerde.java
src/test/java/io/confluent/examples/streams/utils/MockGenericAvroSerializer.java

Continue the work of #242 , #245 , #246 , and #248 by establishing a pattern for GenericRecord Avro tests to use TopologyTestDriver.

MINOR: migrate GenericAvroIntegrationTest to TTD

---

src/main/java/io/confluent/examples/streams/microservices/EmailService.java
src/main/java/io/confluent/examples/streams/microservices/FraudService.java
src/main/java/io/confluent/examples/streams/microservices/InventoryService.java
src/main/java/io/confluent/examples/streams/microservices/OrdersService.java

This PR is an attempt to help reduce the flakiness of some of the microservice tests.  From looking at the logs, it seems it may take a streams app some time to get into a running state, so the idea is to have the tests block until streams goes from `REBALANCING` to a `RUNNING` state
I'm targeting the `3.3.0-post` branch, so this will hit all versions we're responsible for keeping the tests green.

MINOR: Block on streams start until in a RUNNING state

---

src/main/java/io/confluent/examples/streams/WordCountLambdaExample.java
src/test/java/io/confluent/examples/streams/CustomStreamTableJoinIntegrationTest.java

- Changed handling of result of `get` on user-defined store since
stores return a value and a timestamp since 2.3
- Set STATE_DIR_CONFIG to temp directory.

KSTREAMS-2871, KSTREAMS-2870, KSTREAMS-2868: Fix test failures

---

src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java

The `KafkaZkClient` now returns a `Set` instead of a `Seq` for `getAllTopicsInCluster` so we needed to switch to `JavaConverters.setAsJavaSetConverter` method

MINOR: Change set vs seq for java converters

---

docs/index.rst

The docs have been telling people to checkout 'master' for the music example since 4.0, but they should be checking out that version's branch. This was actually correct before 4.0 but let's just replace with |release| everywhere for consistency

Use |release| macro for branch name in docs

---

docker-compose.yml

The music demo app has been broken since 5.2 in part because the topics need to be created with a  replication factor of 3.
Note, this only partially fixes the demo -- see [KSTREAMS-2990](https://confluentinc.atlassian.net/browse/KSTREAMS-2990)

Fix replication factor in docker-compose

---

README.md
src/test/java/io/confluent/examples/streams/AggregateTest.java
src/test/java/io/confluent/examples/streams/IntegrationTestUtils.java
src/test/java/io/confluent/examples/streams/ReduceTest.java
src/test/scala/io/confluent/examples/streams/AggregateScalaTest.scala
src/test/scala/io/confluent/examples/streams/IntegrationTestScalaUtils.scala
src/test/scala/io/confluent/examples/streams/ReduceScalaTest.scala

This is a subset of the original PR at https://github.com/confluentinc/kafka-streams-examples/pull/235 that contains only the new Aggregate + Reduce tests in Java and Scala, plus an updated IntegrationTestUtils (Java) and a new IntegrationTestScalaUtils.

Add new Aggregate and Reduce examples

---

src/test/java/io/confluent/examples/streams/IntegrationTestUtils.java

`IntegrationTestUtils#drainTableOutput()` does not remove null-valued entries from the map that it returns, though it should.
The method should return just the "effective table", not the full changelog (= all records in a table’s changelog). Hence null-valued entries should be removed.

IntegrationTestUtils: correctly handle null keys and null values when draining table output

---

docker-compose.yml

When the 5.3.0-post branch was cut it removed the -SNAPSHOT from all image version number references in the docker-compose but missed the name of the jar
Will talk to tools about fixing this going forward

Remove SNAPSHOT from standalone jar

---

docker-compose.yml

The music demo app has been "broken" for kafka-streams-examples images 5.1.0 and later, where the IQ results were not visible outside the container. 
This PR is targeted at 5.2.0-post since 5.1.0-post mistakenly uses the 5.0.0 image -- will fix in a follow up PR

Set KAFKA_MUSIC_APP_REST_HOST to 0.0.0.0

---

docker-compose.yml

Follow up to [282](https://github.com/confluentinc/kafka-streams-examples/pull/282) because pint merge resulted in conflicts for 5.2.0+

Configure music app REST host

---

src/test/java/io/confluent/examples/streams/microservices/util/MicroserviceTestUtils.java

Although not a great practice, some of the restful integration tests could stand a bump in the timeout. I am doing this in `3.3.0-post` as we've seen the same error in `4.x` and `5.x` branches.

MINOR: Update timeout

---

Jenkinsfile

We should be using the new docker swarm nodes because the pool is much bigger.

Use docker swarm nodes

---

docker-compose.yml

cp-demo: Bump 5.4.x branch
Issue:
Docker image tag got bumped to in-correct value for docker image tags during 5.4.x branch cut.
Solution
- learn about all the changes required for devx repositories both during branch cut & release version bumps.
- address immediate issue by bumping these to 5.4.x-latest
- update branch cut steps to avoid future issues:
https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/582517464/Major+Minor+Release+Release+Branch+Creation+Feature+Freeze#Major/MinorRelease:ReleaseBranchCreation(FeatureFreeze)-DevXFollowups
Automate via tooling - Added jira to fix tooling:
https://confluentinc.atlassian.net/browse/ST-2650

Bump 5.4.x branch

---

Dockerfile
Jenkinsfile
pom.xml

Since this image is built from artifacts and not packages we don't need to create separate docker files for each os type we want to build, which is the pattern we use with the other images that are built from packages. This change will build the same docker file twice but each time using a different docker upstream tag so that it uses a different base image each time. 
I have tested the debian images locally and it worked with cp-demo. Testing of the rhel images with cp-demo is still on going.

ST-2560: Adding support for building debian and rhel images

---

src/test/scala/io/confluent/examples/streams/algebird/CMSStoreTest.scala

Follow up to https://github.com/apache/kafka/pull/7833 that renamed `NoOpRecordCollector` to `MockRecordCollector`.

MINOR: fix broken build

---

src/main/java/io/confluent/examples/streams/ApplicationResetExample.java
src/main/java/io/confluent/examples/streams/GlobalKTablesExample.java
src/main/java/io/confluent/examples/streams/GlobalKTablesExampleDriver.java
src/main/java/io/confluent/examples/streams/JsonToAvroExample.java
src/main/java/io/confluent/examples/streams/JsonToAvroExampleDriver.java

The removed SNAPSHOT suffixes were not automatically removed by
Jenkins.
For an example of the SNAPSHOT suffixes removed by Jenkins
see
https://github.com/confluentinc/kafka-streams-examples/commit/fa1a5e1a159a7777912b8e0ae10dcf871a06d183

Remove SNAPSHOT suffix from versions in comments

---

pom.xml
src/main/java/io/confluent/examples/streams/JsonToAvroExample.java
src/main/java/io/confluent/examples/streams/JsonToAvroExampleDriver.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExample.java
src/main/java/io/confluent/examples/streams/microservices/OrderDetailsService.java

Schema registry added pluggable schemas in master, `Avro` dependency needed to get upgraded to 1.9.1.  This PR is needed to fix the kafka-streams-examples master build failures.

MINOR: Change Avro dependency required for schema registry updates

---

Dockerfile.deb9
Dockerfile.rhel8

These labels are required to pass the RedHat certification process for uploading images to the container registry.

ST-2560: Adding labels required by RedHat container registry

---

docker-compose.yml

Submitted a tools ticket so they can investigate why this is broken before the 5.5.0 and 5.4.1 release/branch cut (I hope).

Docker image names were not updated in 5.4.0

---

docs/index.rst

https://confluentinc.atlassian.net/browse/DOCS-2174
- Updated formatting on the ksql Streams examples doc to make it easier to copy-paste examples, and to follow the steps
- The original feedback on the associated Docs ticket was that the example didn't run, but I ran through it on 5.5.0 and it runs fine. I responded to the customer on [this Google email](https://groups.google.com/a/confluent.io/d/msg/docs/p136BvlYoKU/7YxRKu2hAgAJ).
- I didn't know how to test a build of this, so I don't know if my changes will render properly in HTML when built. @JimGalasyn maybe you can show me how to do this?
- 5.3.0-post
Signed-off-by: Victoria Bialas <vicky@confluent.io>

DOCS-2174 Formatting improvements Kafka Streams Example docs

---

include/etc/confluent/docker/run

We don't want to print the environment variables in the logs during startup because they contain sensitive data.

ST-3599: Remove show_env function because it exposes secrets

---

Jenkinsfile

Failures here are sent to #tools-notifcations, they should be sent to the streams slack channel.

Alert slack streams on-call channel on failures

---

src/main/scala/io/confluent/examples/streams/MapFunctionScalaExample.scala
src/main/scala/io/confluent/examples/streams/WordCountScalaExample.scala

I hope this fixed the spotbug issue:
```
19:33:52  [INFO] Total bugs: 8
[2020-06-02T02:33:52.207Z] [ERROR] Write to static field io.confluent.examples.streams.MapFunctionScalaExample$.config from instance method io.confluent.examples.streams.MapFunctionScalaExample$.delayedEndpoint$io$confluent$examples$streams$MapFunctionScalaExample$1() [io.confluent.examples.streams.MapFunctionScalaExample$] At MapFunctionScalaExample.scala:[line 105] ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD
[2020-06-02T02:33:52.207Z] [ERROR] Write to static field io.confluent.examples.streams.MapFunctionScalaExample$.scala$App$$_args from instance method io.confluent.examples.streams.MapFunctionScalaExample$.scala$App$$_args_$eq(String[]) [io.confluent.examples.streams.MapFunctionScalaExample$] At …
```

HOTFIX: fix spotbug error

---

Jenkinsfile

[This PR](https://github.com/confluentinc/kafka-streams-examples/pull/343) should have been merged to 3.3.x, not 5.3.x

Send alerts to the #streams-alerts slack channel

---

pom.xml
src/main/scala/io/confluent/examples/streams/MapFunctionScalaExample.scala
src/main/scala/io/confluent/examples/streams/WordCountScalaExample.scala

Since the upgrade to 2.13, spotbugs is choking on Scala's generated
bytecode. See #340 for the errors. 
The prior fix #340 unintentionally broke the examples by changing
the applications from `object` to `class`, which makes them no longer
runnable. I.e., this change converted the main method to a non-static
method, so there wouldn't be any way to actually run the examples
on the console.
Since this repo doesn't contain any production code (just examples),
we can just disable spotbugs. We still have compiler warnings as
errors and checkstyle.

HOTFIX: revert #340 and disable spotbugs

---

pom.xml
src/main/java/io/confluent/examples/streams/microservices/AddInventory.java
src/main/java/io/confluent/examples/streams/microservices/EmailService.java
src/main/java/io/confluent/examples/streams/microservices/FraudService.java
src/main/java/io/confluent/examples/streams/microservices/InventoryService.java
src/main/java/io/confluent/examples/streams/microservices/OrderDetailsService.java
src/main/java/io/confluent/examples/streams/microservices/OrdersService.java
src/main/java/io/confluent/examples/streams/microservices/PostOrdersAndPayments.java
src/main/java/io/confluent/examples/streams/microservices/Service.java
src/main/java/io/confluent/examples/streams/microservices/ValidationsAggregatorService.java
src/main/java/io/confluent/examples/streams/microservices/domain/Schemas.java
src/main/java/io/confluent/examples/streams/microservices/domain/beans/OrderBean.java
src/main/java/io/confluent/examples/streams/microservices/util/ConsumeCustomers.java
src/main/java/io/confluent/examples/streams/microservices/util/ConsumeOrders.java
src/main/java/io/confluent/examples/streams/microservices/util/ConsumePayments.java
src/main/java/io/confluent/examples/streams/microservices/util/MicroserviceUtils.java
src/main/java/io/confluent/examples/streams/microservices/util/Paths.java
src/main/java/io/confluent/examples/streams/microservices/util/ProduceCustomers.java
src/main/java/io/confluent/examples/streams/microservices/util/ProduceOrders.java
src/main/java/io/confluent/examples/streams/microservices/util/ProducePayments.java
src/main/java/io/confluent/examples/streams/utils/MonitoringInterceptorUtils.java
src/test/java/io/confluent/examples/streams/microservices/EmailServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/EndToEndTest.java
src/test/java/io/confluent/examples/streams/microservices/FraudServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/InventoryServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/OrderDetailsServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/OrdersServiceTest.java
src/test/java/io/confluent/examples/streams/microservices/ValidationsAggregatorServiceTest.java

DEVX-1881: Update microservices code to work with secure clusters and SR.  Configuration values can be passed in with properties files to the various services.
The microservices have been modified to accept CLI named arguments instead of positional arguments.

DEVX-1881: Update microservices code to work with secure services

---

docs/index.rst

This PR is a set of three:
1. https://github.com/confluentinc/examples/pull/784: code changes, strip adoc/README, deprecate local install
2. https://github.com/confluentinc/kafka-streams-examples/pull/358: rst source
3. https://github.com/confluentinc/docs/pull/5630: for staging only --> DO NOT MERGE

DEVX-1692: Move music demo ADOC markdown to docs

---

pom.xml

Similar fix to https://github.com/confluentinc/common-docker/pull/111
Include the missing test dependencies to fix the build issue:
```
[2020-09-27T19:46:15.731Z] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.005 s <<< FAILURE! - in io.confluent.examples.streams.SpecificAvroIntegrationTest
[2020-09-27T19:46:15.731Z] [ERROR] io.confluent.examples.streams.SpecificAvroIntegrationTest  Time elapsed: 0.004 s  <<< ERROR!
12:46:15  java.lang.NoClassDefFoundError: org/junit/jupiter/api/Assertions
12:46:15  	at io.confluent.examples.streams.SpecificAvroIntegrationTest.startKafkaCluster(SpecificAvroIntegrationTest.java:62)
12:46:15  Caused by: java.lang.ClassNotFoundException: org.junit.jupiter.api.Assertions
12:46:15  	at …
```

MINOR: Add org.junit.jupiter:junit-jupiter-api as Test Dependency

---

Jenkinsfile
pom.xml

Setting the jenkins config to use nano versioning. Removed all of the snapshot versions and replaced with nano versions. Updated all of the dependency versions.
These changes will be merged during phase two of the nano versioning roll out.

ST-3461: Nanover rollout

---

README.md

As reported by @miguno , let's fix the link to the developer guide to point to https://docs.confluent.io/platform/current/streams/developer-guide/index.html

DOCS-6826: Fix link to developer guide

---

src/main/java/io/confluent/examples/streams/microservices/OrdersService.java
src/test/java/io/confluent/examples/streams/microservices/OrdersServiceTest.java

With https://github.com/apache/kafka/pull/9978 we start to lock the state directory and disallow to share it across multiple `KafkaStreams` instances.

MINOR: use isolated state.dir for each KafkaStreams client

---

src/main/java/io/confluent/examples/streams/microservices/OrdersService.java
src/test/java/io/confluent/examples/streams/microservices/OrdersServiceTest.java

Cherry-pick #375 from `master` to `6.0.x`
https://issues.apache.org/jira/browse/KAFKA-10716 that introduced the issue was cherry-picked to AK `2.7` and `2.6` branches.

MINOR: use isolated state.dir for each KafkaStreams client (#375)

---

src/main/java/io/confluent/examples/streams/GlobalKTablesExample.java
src/main/java/io/confluent/examples/streams/JsonToAvroExample.java
src/main/java/io/confluent/examples/streams/JsonToAvroExampleDriver.java
src/main/java/io/confluent/examples/streams/PageViewRegionExample.java
src/main/java/io/confluent/examples/streams/PageViewRegionExampleDriver.java
src/main/java/io/confluent/examples/streams/PageViewRegionLambdaExample.java
src/main/java/io/confluent/examples/streams/SessionWindowsExample.java
src/main/java/io/confluent/examples/streams/SessionWindowsExampleDriver.java
src/main/java/io/confluent/examples/streams/TopArticlesExampleDriver.java
src/main/java/io/confluent/examples/streams/TopArticlesLambdaExample.java
src/main/java/io/confluent/examples/streams/WikipediaFeedAvroExample.java
src/main/java/io/confluent/examples/streams/WikipediaFeedAvroExampleDriver.java
src/main/java/io/confluent/examples/streams/WikipediaFeedAvroLambdaExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExample.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExampleDriver.java
src/test/java/io/confluent/examples/streams/GenericAvroIntegrationTest.java
src/test/java/io/confluent/examples/streams/SessionWindowsExampleTest.java
src/test/java/io/confluent/examples/streams/SpecificAvroIntegrationTest.java
src/test/java/io/confluent/examples/streams/TopArticlesLambdaExampleTest.java
src/test/java/io/confluent/examples/streams/WikipediaFeedAvroExampleTest.java
src/test/java/io/confluent/examples/streams/WikipediaFeedAvroLambdaExampleTest.java
src/test/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExampleTest.java
src/test/scala/io/confluent/examples/streams/GenericAvroScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/SpecificAvroScalaIntegrationTest.scala

1. Removed AbstractKafkaAvroSerDeConfig usage
2. Removed unused imports.
Local tested with regular mvn lifecycle: compile and test
#336

Issue#336 - Remove deprecated AbstractKafkaAvroSerDeConfig usage

---

src/main/java/io/confluent/examples/streams/interactivequeries/MetadataService.java
src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesRestService.java
src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/MusicPlaysRestService.java
src/main/java/io/confluent/examples/streams/microservices/util/MicroserviceUtils.java
src/test/java/io/confluent/examples/streams/IntegrationTestUtils.java
src/test/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExampleTest.java

Several long-deprecated methods are being dropped from Kafka Streams.
Unfortunately, we were still using several of them.

MINOR: remove dropped methods

---

src/test/java/io/confluent/examples/streams/StreamToStreamJoinIntegrationTest.java

Stream-Stream left-/outer-joins got improved via
https://issues.apache.org/jira/browse/KAFKA-10847 to avoid spurious
left/outer join results.
This PR updates the stream-stream join test to match the new join
implemenation.

MINOR: Update test to match new opererator implementation

---

src/test/scala/io/confluent/examples/streams/algebird/CMSStoreTest.scala

The `InternalMockProcessorContext` in kafka-streams now requires two generic parameters. The `CMSStoreTest.scala` was failing because needed to pass the new key/value parameters to the `InternalMockProcessorContext` class. This PR fixes the tests.

Fix CMSStoreTest.scala issue with InternalMockProcessorContext

---

src/test/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExampleTest.java

Running this test locally, if failed reliably with the 30sec timeout and the issue went await with the 60sec timeout.

MINOR: bump timeout to stabilize test

---

src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java

In [#1936](https://github.com/confluentinc/schema-registry/commit/06738ad7ce75cb1105a65d8356938751d7d68273#diff-685a652ce1af196ad342417568034ad869e6f3875a886566652064935fc64bdeL645-L655), SchemaRegistry started to enforce that `KAFKASTORE_BOOTSTRAP_SERVERS_CONFIG` be set, rather than allowing the app to use either that or `KAFKASTORE_CONNECTION_URL_CONFIG` which turned out to. be a deprecated zookeeper-specific config that we apparently still used.

Migrate off of deprecated SchemaRegistry zk config, use bootstrap servers config instead

---

src/test/java/io/confluent/examples/streams/FanoutLambdaIntegrationTest.java

We recently [changed the default serde to be null](https://github.com/apache/kafka/pull/10813) and therefore need to update this test to make sure it properly sets a key serde

fix: update lambda integration test with new null serde changes

---

src/main/scala/io/confluent/examples/streams/algebird/CMSStoreChangeLogger.scala
src/test/java/io/confluent/examples/streams/microservices/InventoryServiceTest.java

saw a bunch of failures here: https://confluentinc.atlassian.net/browse/KSQL-6263
recent logs indicate that there was a parameter mismatch:
`[2021-08-09T13:45:35.897Z] [ERROR] /home/jenkins/workspace/nc_kafka-streams-examples_master/src/main/scala/io/confluent/examples/streams/algebird/CMSStoreChangeLogger.scala:36: error: type mismatch;
[2021-08-09T13:45:35.897Z] [ERROR]  found   : Boolean(false)
[2021-08-09T13:45:35.897Z] [ERROR]  required: String
[2021-08-09T13:45:35.897Z] [ERROR]   private val topic = ProcessorStateManager.storeChangelogTopic(context.applicationId, storeName, false)`
the current internal api takes `public static String storeChangelogTopic(final String applicationId, final String storeName, final String namedTopology)`

Correct internal API to use string instead of boolean

---

src/main/scala/io/confluent/examples/streams/algebird/CMSStoreChangeLogger.scala

The changed API is public, but it's not release yet, thus there is no upstream deprecation necessary, but the KIP was changed.

MINOR: fix compile error

---

src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesDriver.java
src/main/java/io/confluent/examples/streams/microservices/AddInventory.java
src/main/java/io/confluent/examples/streams/microservices/PostOrdersAndPayments.java
src/main/java/io/confluent/examples/streams/microservices/util/ProduceCustomers.java
src/main/java/io/confluent/examples/streams/microservices/util/ProduceOrders.java
src/main/java/io/confluent/examples/streams/microservices/util/ProducePayments.java
src/test/java/io/confluent/examples/streams/ApplicationResetIntegrationTest.java
src/test/java/io/confluent/examples/streams/CustomStreamTableJoinIntegrationTest.java
src/test/java/io/confluent/examples/streams/SpecificAvroIntegrationTest.java
src/test/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExampleTest.java
src/test/java/io/confluent/examples/streams/microservices/util/MicroserviceTestUtils.java
src/test/scala/io/confluent/examples/streams/GenericAvroScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/SpecificAvroScalaIntegrationTest.scala

see failures here: https://jenkins.confluent.io/job/confluentinc/job/kafka-streams-examples/job/7.0.x/604/testReport/
testing done: ran test

update examples to use retries of 1 for idempotent producer

---

.gitignore
.mvn/wrapper/MavenWrapperDownloader.java
.mvn/wrapper/maven-wrapper.properties

A few commits need to be cherry-picked back to 7.2.x to make the Maven wrapper work.

Fix maven wrapper 7.2.x

---

src/main/scala/io/confluent/examples/streams/algebird/CMSStore.scala
src/main/scala/io/confluent/examples/streams/algebird/CMSStoreChangeLogger.scala
src/test/scala/io/confluent/examples/streams/ProbabilisticCountingScalaIntegrationTest.scala
src/test/scala/io/confluent/examples/streams/algebird/CMSStoreTest.scala

Upstream change broke the code:
https://github.com/apache/kafka/commit/a6c5a74fdbdce9a992b47706913c920902cda28c#diff-84b3ac8682467c5c0fe024978e60e02c6f4583d3c72171ff20c41a419ca04b84)

MINOR: fix master

---

pom.xml

Cherry-pick fix https://github.com/confluentinc/kafka-streams-examples/pull/429 to 5.5.x.

security fix: Migrate from log4j to reload4j

---

pom.xml

Cherry-pick fix https://github.com/confluentinc/kafka-streams-examples/pull/429 to 6.0.x.

security fix: Migrate from log4j to reload4j 

---

pom.xml

Not needed after https://github.com/confluentinc/common/pull/489.

APIF-3117: Unpin scala version.

---

pom.xml

Getting following error in Jenkins - https://jenkins.confluent.io/job/confluentinc/job/kafka-streams-examples/job/master/9245/console . I could re-produce it locally with `mvn test`, and it's gone after adding the `snappy-java` dependency
```
[2024-01-25 18:03:24,546] ERROR [Thread-1] Thread Thread[Thread-1,5,main] died (org.apache.zookeeper.server.NIOServerCnxnFactory)
13:03:24  java.lang.NoClassDefFoundError: org/xerial/snappy/SnappyOutputStream
13:03:24  	at org.apache.zookeeper.server.persistence.Util.makeSnapshotName(Util.java:97)
13:03:24  	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.save(FileTxnSnapLog.java:478)
13:03:24  	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:300)
13:03:24  	at …
```

[hotfix] add snappy-java dependency to fix jenkins pipeline

---

service.yml

Finishing the semaphore migration is blocked, see https://confluentinc.atlassian.net/browse/KSTREAMS-5779.
Meanwhile, the semaphore job is failing and creating lots of testbreak ticket noise, so I'm trying to disable it.

chore: disable semaphore

---

src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java

We rely on some Kafka internal code, which was changed recently via https://github.com/apache/kafka/commit/eea369af947dcff567f849183ba2217ac5e9a2ba

MINOR: fix compilation error

---

src/test/java/io/confluent/examples/streams/WikipediaFeedAvroLambdaExampleTest.java
src/test/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExampleTest.java
src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java

Fix compilation failures and warnings due to internal config renamings (and one external deprecation).

MINOR: Update config names

---

service.yml

As per comments on https://confluentinc.atlassian.net/browse/KSTREAMS-5737, we should just disable tag builds

MINOR: disable tag builds

---

src/test/java/io/confluent/examples/streams/microservices/util/MicroserviceTestUtils.java

Commit 61baa7ac6bb871797197d9289a848a0d4f587ced in Kafka moved around the internal fields for these public configs.
We should not depend on the internal fields, otherwise we will keep breaking here. Just use the public API.

MINOR: Fix config names

---

service.yml

While migrating to semaphoreCI, we want to have our CP docker images signed in order to comply to container hardening/ FedRamp requirements. To enable image signing, we just need to include sign_image: true in service.yml and apply the changes by running service bot. Further described in wiki

KSTREAMS-5737: Enable signing

---

service.yml

There was a tricky ... hidden in the task definition that needed to be replaced which wasn't mentioned anywere.

KSTREAMS-5737: Fix task definition

---

service.yml

I was informed that the wiki is incorrect and we shouldn't set `branches`.

MINOR: Update service.yml

---

service.yml

https://semaphore.ci.confluent.io/workflows/69a1c8ee-e4c6-4267-a33c-796154645bdc?pipeline_id=269ebc08-154c-442a-9553-f4355af3ff43 7.0.x docker build run ^^ shows that deploy blocks were skipped.
Looks like, we’ll need to set use_packages as true as per template https://github.com/confluentinc/cc-service-bot/blob/master/servicebot/templates/semaphore_pipeline_cp_dockerfile.yml.jinja2#L172

KSTREAMS-5737 Set use_packages to true

---

src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java
src/test/java/io/confluent/examples/streams/kafka/KafkaEmbedded.java

We depend on broker internal classes which got changed upstream:
- https://github.com/apache/kafka/commit/1b301b30207ed8fca9f0aea5cf940b0353a1abca
- https://github.com/apache/kafka/commit/363f4d28472793029f7ed3c0f156406f11a3bd7e
- https://github.com/apache/kafka/commit/ecb2dd4cdc4b83df7a97dc37e4e419ad4490ae10
This PR updates our code accordingly, to match the new internals.

HOTIFX: fix compilation errors

---

.mvn/wrapper/maven-wrapper.properties

SemaphoreCI builds have started failing 
https://semaphore.ci.confluent.io/jobs/7cfbf367-93b5-4d4f-bf9c-c89619e2b172#L239
https://semaphore.ci.confluent.io/jobs/14b32e04-7710-417a-8564-3d801938c03e#L241 
confluent-packaging-tools bucket has been migrated to new aws account, updating the ref

Update confluent-packaging-tools ref in mvn properties

---

src/main/scala/io/confluent/examples/streams/algebird/CMSStore.scala
src/test/java/io/confluent/examples/streams/ApplicationResetIntegrationTest.java

Fixing build. 
1 - Remove unsupported method that was overriding one that was recently removed with upstream change https://github.com/apache/kafka/pull/16906/files#diff-7fe11ab5459b6c6e35ee9699639025e1ce8814b8b603596f69f6e45a011e1675
2 - fix wrong param that was causing abrupt failure in ApplicationResetIntegrationTest (test crashed). Mixed in the logs there was:
bootstrap-servers is not a recognized option
Option (* = required) Description
--bootstrap-server <String: server to The server(s) to connect to....
All test pass locally after these fixes.

MINOR: fix build broken references and params

---

src/main/scala/io/confluent/examples/streams/algebird/CMSStore.scala
src/test/java/io/confluent/examples/streams/ApplicationResetIntegrationTest.java

Reverts https://github.com/confluentinc/kafka-streams-examples/pull/523 which only applies to CP 8.0 release.

MINOR: restore pre CP-8.0 code

---

pom.xml
src/main/java/io/confluent/examples/streams/microservices/AddInventory.java
src/main/java/io/confluent/examples/streams/microservices/EmailService.java
src/main/java/io/confluent/examples/streams/microservices/FraudService.java
src/main/java/io/confluent/examples/streams/microservices/InventoryService.java
src/main/java/io/confluent/examples/streams/microservices/OrderDetailsService.java
src/main/java/io/confluent/examples/streams/microservices/OrdersService.java
src/main/java/io/confluent/examples/streams/microservices/PostOrdersAndPayments.java
src/main/java/io/confluent/examples/streams/microservices/ValidationsAggregatorService.java
src/main/java/io/confluent/examples/streams/microservices/util/ConsumeCustomers.java
src/main/java/io/confluent/examples/streams/microservices/util/ConsumeOrders.java
src/main/java/io/confluent/examples/streams/microservices/util/ConsumePayments.java
src/main/java/io/confluent/examples/streams/microservices/util/ProduceCustomers.java
src/main/java/io/confluent/examples/streams/microservices/util/ProduceOrders.java
src/main/java/io/confluent/examples/streams/microservices/util/ProducePayments.java

Splitting out one version bump from https://github.com/confluentinc/kafka-streams-examples/pull/541 to apply required code changes.

chore(deps): update commons-cli version
